In [1]:
%load_ext autoreload
%autoreload 2

In [5]:
import tiktoken
import torch

tokenizer = tiktoken.get_encoding("cl100k_base")
batch = []

txt1 = "Every effort moves you"
txt2 = "Every day holds a"

batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)
print(batch)

tensor([[11769,  5149, 11031,   499],
        [11769,  1938, 10187,   264]])


In [ ]:
from dummy_model import DummyGPTModel, load_yaml

torch.manual_seed(123)
config = load_yaml("config/model_config.yaml")["model"]
print(config)

In [ ]:
model = DummyGPTModel(config)
logits = model(batch)
print(f"Output shape: {logits.shape}")
print(logits)

Output tensor has two rows corresponding to the text text samples, four tokens (rows), and 100257 dimensional-vector (tokenizer vocab size)

## Normalizing activations with layer normalizations

The idea behind layer norm is to have the activations of a nn have a mean of 0 and variance of 1, aka unit variance.
Typically applied before and after the multi-head attention module, and before the output layer.
Activations are just the outputs of a neural network layer.

In [ ]:
# create 2 training examples with 5 dimensions each
import torch.nn as nn
torch.manual_seed(123)
batch_example = torch.randn(2, 5)
layer = nn.Sequential(nn.Linear(5, 6), nn.ReLU())
out = layer(batch_example)
print(out)

In [ ]:
mean = out.mean(dim=-1, keepdim=True)
var = out.var(dim=-1, keepdim=True)
print(mean)
print(var)

In [ ]:
out_norm = (out - mean) / torch.sqrt(var)
mean = out_norm.mean(dim=-1, keepdim=True)
var = out_norm.var(dim=-1, keepdim=True)
print(out_norm)
print(f"mean: {mean}")
print(f"var: {var}")

In [ ]:
torch.set_printoptions(sci_mode=False)
print(mean)

### Using Layer norm module

In [ ]:
from architecture import LayerNorm

ln = LayerNorm(emb_dim=5)
out_ln = ln(batch_example)
mean = out_ln.mean(dim=-1, keepdim=True)
var = out_ln.var(dim=-1, unbiased=False, keepdim=True)
print(mean)
print(var)

# GELU activation

In [ ]:
from architecture import GELU
import matplotlib.pyplot as plt

gelu, relu = GELU(), nn.ReLU()

x = torch.linspace(-3, 3, 100)
y_gelu, y_relu = gelu(x), relu(x)
plt.figure(figsize=(8, 3))
for i, (y, label) in enumerate(zip([y_gelu, y_relu], ["GELU", "RELU"]), 1):
    plt.subplot(1, 2, i)
    plt.plot(x, y)
    plt.title(f"{label} activation function")
    plt.xlabel("x")
    plt.ylabel(f"{label}")
    plt.grid(True)
plt.tight_layout()
plt.show()

In [ ]:
from architecture import FeedForward

ffn = FeedForward(config)
x = torch.rand(2, 3, 768)

ffn(x)


In [ ]:
ffn(x).shape

## Residual connections

Fight the problem of vanishing gradients, where gradients become progressively smaller as they travel through backprop.
Shortcut connections involve adding the inputs of a layer to another's (can be their own) output, effectively skipping the layer. The gradients denote the mean absolute gradient.

## Connecting attention and linear layers in a transformer block

Now implementing the transformer block. Blocks are modelled after the GPT-2 architecture: 

Layer norm 1 -> MHA -> dropout 1 -> add Residual 1 -> Layer norm 2 -> FFN (linear -> GELU -> linear) -> dropout 2 -> add Residual 2

In [7]:
import os
import sys
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

from architecture import TransformerBlock
from dummy_model import load_yaml

torch.manual_seed(123)
x = torch.rand(2, 4, 768)

config = load_yaml("config/model_config.yaml")["model"]
block = TransformerBlock(config)
output = block(x)
print(output)
print(output.shape)

tensor([[[-0.0055,  0.0972, -0.1122,  ...,  1.2889,  0.2623,  0.6685],
         [ 0.0023, -0.2369,  0.1720,  ...,  0.5952,  0.2497,  0.7447],
         [ 0.4673,  0.4472,  0.1791,  ...,  1.2525,  0.3045,  0.7750],
         [ 0.0662,  0.7224,  0.9206,  ...,  0.4790,  0.7428,  0.7015]],

        [[ 0.3622,  1.2144,  0.5221,  ...,  0.1854,  0.0111, -0.5034],
         [-0.0225,  0.7789,  0.2770,  ...,  0.1734,  0.5419,  0.1143],
         [ 0.7425,  0.4013,  0.3211,  ...,  0.3268,  0.7523, -0.1642],
         [ 0.5745,  0.6241,  0.4410,  ...,  1.1963,  1.2650,  0.2243]]],
       grad_fn=<AddBackward0>)
torch.Size([2, 4, 768])


## Coding the GPT model

In [10]:
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")
batch = []

txt1 = "Every effort moves you"
txt2 = "Every day holds a"

batch.append(torch.tensor(tokenizer.encode(txt1)))
batch.append(torch.tensor(tokenizer.encode(txt2)))
batch = torch.stack(batch, dim=0)

In [15]:
from architecture import GPTModel
torch.manual_seed(123)

model = GPTModel(config)
out = model(batch)
print(f"input batch: {batch}")
print(f"output shape {out.shape}")
print(out)

input batch: tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])
output shape torch.Size([2, 4, 50257])
tensor([[[ 0.3613,  0.4222, -0.0711,  ...,  0.3483,  0.4661, -0.2838],
         [-0.1792, -0.5660, -0.9485,  ...,  0.0477,  0.5181, -0.3168],
         [ 0.7120,  0.0332,  0.1085,  ...,  0.1018, -0.4327, -0.2553],
         [-1.0076,  0.3418, -0.1190,  ...,  0.7195,  0.4023,  0.0532]],

        [[-0.2564,  0.0900,  0.0335,  ...,  0.2659,  0.4454, -0.6806],
         [ 0.1230,  0.3653, -0.2074,  ...,  0.7705,  0.2710,  0.2246],
         [ 1.0558,  1.0318, -0.2800,  ...,  0.6936,  0.3205, -0.3178],
         [-0.1565,  0.3926,  0.3288,  ...,  1.2630, -0.1858,  0.0388]]],
       grad_fn=<UnsafeViewBackward0>)


In [14]:
from architecture import GPTModelFlashAttn
torch.manual_seed(123)

flash_model = GPTModelFlashAttn(config)
out = flash_model(batch)
print(f"input batch: {batch}")
print(f"output shape {out.shape}")
print(out)

input batch: tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])
output shape torch.Size([2, 4, 50257])
tensor([[[ 0.3613,  0.4222, -0.0711,  ...,  0.3483,  0.4661, -0.2838],
         [-0.1792, -0.5660, -0.9485,  ...,  0.0477,  0.5181, -0.3168],
         [ 0.7120,  0.0332,  0.1085,  ...,  0.1018, -0.4327, -0.2553],
         [-1.0076,  0.3418, -0.1190,  ...,  0.7195,  0.4023,  0.0532]],

        [[-0.2564,  0.0900,  0.0335,  ...,  0.2659,  0.4454, -0.6806],
         [ 0.1230,  0.3653, -0.2074,  ...,  0.7705,  0.2710,  0.2246],
         [ 1.0558,  1.0318, -0.2800,  ...,  0.6936,  0.3205, -0.3178],
         [-0.1565,  0.3926,  0.3288,  ...,  1.2630, -0.1858,  0.0388]]],
       grad_fn=<UnsafeViewBackward0>)


In [20]:
total_params = sum(p.numel() for p in model.parameters())
print(f"{total_params:,}")

163,009,536


### Excercise 4.1 - Number of parameters in FFN and MHA modules

In [27]:
p_ffn = sum(p.numel() for p in model.trf_blocks[0].ff.parameters())
print(f"{p_ffn:,}")

p_mha = sum(p.numel() for p in model.trf_blocks[0].att.parameters())
print(f"{p_mha:,}")

p_flash_mha = sum(p.numel() for p in flash_model.trf_blocks[0].att.parameters())
print(f"{p_flash_mha:,}")

4,722,432
2,360,064
2,360,064


In [30]:
# calculating the mem requirements for the model

size_bytes = total_params * 4
size_mb = size_bytes / (1024 ** 2)
print(f"Total size of the model is {size_mb:.2f} MB")

Total size of the model is 621.83 MB
